#!/usr/bin/env groovy
pipeline {
    agent any
    options {
        gitLabConnection gitLabConnection: 'Gitlab', jobCredentialId: 'Gitlab_Token', useAlternativeCredential: true
        gitlabCommitStatus('Build with Jenkins')
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')
    }
    tools {
        jdk 'openJdk17'
        maven 'maven3.8.8'
    }
    environment {
        POM_VERSION = readMavenPom().getVersion()
        IS_SNAPSHOT = readMavenPom().getVersion().endsWith('-SNAPSHOT')
    }
    stages {
        stage('Build Project') {
            steps {
                sh '''
                    mvn clean package
                   '''
            }
        }
        stage('Junit Reports') {
            steps {
                jacoco(
                    execPattern: '**/**.exec',
                    classPattern: '**/classes',
                    sourcePattern: '**/src/main/java',
                    inclusionPattern: '**/*.class',
                    exclusionPattern: '**/*Test*.class'
                )
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        mvn clean verify sonar:sonar -Dsonar.projectName='Demo' -Dsonar.branch.name=${BRANCH_NAME}
                       '''
                }
            }
        }
        stage('Deploy to Nexus') {
            when {
                anyOf {
                    allOf {
                      branch 'main'
                      environment name: 'IS_SNAPSHOT', value: 'false'
                    }
                    allOf {
                      branch 'develop'
                      environment name: 'IS_SNAPSHOT', value: 'true'
                    }
                }
            }
            steps {
                configFileProvider([configFile('ee9017fa-4f60-472b-b428-3e44dc457159')]) {
                    sh '''
                        mvn deploy
                       '''
                }
            }
        }
        stage('Push Tag') {
            steps {
                withCredentials([gitUsernamePassword(credentialsId: 'GitLab_Account', gitToolName: 'Default')]) {
                    sh 'git fetch origin'
                    catchError {
                        sh 'git tag -d v${POM_VERSION}'
                        sh 'git push --delete origin v${POM_VERSION}'
                    }
                    sh 'git tag v${POM_VERSION}'
                    sh 'git push origin v${POM_VERSION}'
                }
            }
        }
    }
}
