#!/usr/bin/env groovy
pipeline {
    agent any
    tools {
        jdk 'openJdk17'
        maven 'maven3.8.8'
    }
    stages {
        stage('Build Project') {
            steps {
                sh '''
                    mvn clean package
                   '''
            }
        }
        stage('Junit Reports') {
            steps {
                jacoco(
                    execPattern: '**/**.exec',
                    classPattern: '**/classes',
                    sourcePattern: '**/src/main/java',
                    inclusionPattern: '**/*.class',
                    exclusionPattern: '**/*Test*.class'
                )
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        mvn clean verify sonar:sonar -Dsonar.projectName='Demo' -Dsonar.branch.name=${BRANCH_NAME}
                       '''
                }
            }
        }
    }
}
